name: MLOps CI Pipeline

on:
  push:
    branches: [main]

jobs:
  test-suite:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Requirements.txt

      - name: Run tests
        run: pytest

  train-and-quantize:
    needs: test-suite
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -r Requirements.txt

      - name: Train model
        run: python src/train.py

      - name: Quantize model
        run: python src/quantize.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trained-models
          path: |
            model.joblib
            unquant_params.joblib
            quant_params.joblib

  build-and-test-container:
    needs: train-and-quantize
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t mlops-pipeline .

      - name: Run Docker container
        run: docker run --rm mlops-pipeline


      - name: Login to Docker Hub platform
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push to Docker Hub
        if: success()
        run: |
          docker tag mlops-pipeline ${{ secrets.DOCKER_NAME }}/mlops-pipeline
          docker push ${{ secrets.DOCKER_NAME }}/mlops-pipeline
          echo "Docker image has been pushed successfully in github."
